.Dd January 3, 2018
.Dt CONTROL-BRIGHTNESS 1
.Os
.Sh NAME
.Nm control-brightness
.Nd brightness controls
.Sh SYNOPSIS
.Nm
.Op Fl + Ar VALUE
.Sh DESCRIPTION
.Nm
allows the user to control the brightness by specifying a
.I VALUE
to add/remove to the current brightness.
.Pp
The brightness level cannot be lower than 0% and higher than 100%.
.Sh EXAMPLES
This section contains some examples of how to use the program.
.Pp
This command will raise the brightness by 5%:
.nf
.RS
control-brightness "+5%"
.RE
