directory: ~/Music
library: ~/Music/library.db
plugins: mbsync chroma mpdupdate smartplaylist mpdstats embedart inline missing zero
art_filename: cover
import:
    move: yes
    write: yes
    log: beets.log
ui:
    color: yes
threaded: yes
paths:
    default: $genre/$albumartist/$album%aunique{}/%if{$multidisc,CD$disc/}/$track $title
    singleton: Singleton/$artist - $title

item_fields:
    multidisc: 1 if disctotal > 1 else 0

mpd:
    host: localhost
    port: 6600

smartplaylist:
    playlist_dir: ~/.config/mpd/playlists
    playlists:
        - name: already_listened.m3u
          query: 'play_count:1..'
        - name: movies_and_games.m3u
          query: 'genre::(Game|Soundtrack|Soundtracks)'
        - name: movies_games_and_post_rock.m3u
          query: 'genre::(Game|Soundtrack|Soundtracks|Post-Rock|post-rock)'

embedart:
    auto: yes
    compare_threshold: 95

zero:
    fields: comments
    comments: [EAC, LAME, from.+collection, '([Rr]ipped|[Ee]ncoded)\sby']
    update_dabase: true

missing:
    format: $albumartist - $album - $title
    count: yes
    total: yes
